import type { CSSProperties } from "react";
import {
  Activity,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  Bookmark,
  BookmarkPlus,
  Box,
  Building2,
  Calendar,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  Circle,
  Clock,
  Copy,
  Download,
  FileArchive,
  Filter,
  GitBranch,
  GitCommit,
  Globe,
  Hash,
  Layers,
  Link2,
  Loader,
  Lock,
  LogIn,
  LogOut,
  MoreHorizontal,
  Package,
  Package2,
  Plus,
  Search,
  SearchX,
  Send,
  Settings,
  Shield,
  SquareStack,
  Star,
  Tag,
  Upload,
  UploadCloud,
  User,
  UserMinus,
  UserPlus,
  Users,
  X,
  type LucideIcon,
} from "lucide-react";

/** Lucide line icons, looked up by the design's data-lucide names. 1.75 stroke. */
const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  "alert-triangle": AlertTriangle,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  bookmark: Bookmark,
  "bookmark-plus": BookmarkPlus,
  box: Box,
  "building-2": Building2,
  calendar: Calendar,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "chevrons-up-down": ChevronsUpDown,
  circle: Circle,
  clock: Clock,
  copy: Copy,
  download: Download,
  "file-archive": FileArchive,
  filter: Filter,
  "git-branch": GitBranch,
  "git-commit": GitCommit,
  globe: Globe,
  hash: Hash,
  layers: Layers,
  "link-2": Link2,
  loader: Loader,
  lock: Lock,
  "log-in": LogIn,
  "log-out": LogOut,
  "more-horizontal": MoreHorizontal,
  package: Package,
  "package-2": Package2,
  plus: Plus,
  search: Search,
  "search-x": SearchX,
  send: Send,
  settings: Settings,
  shield: Shield,
  "square-stack": SquareStack,
  star: Star,
  tag: Tag,
  upload: Upload,
  "upload-cloud": UploadCloud,
  user: User,
  "user-minus": UserMinus,
  "user-plus": UserPlus,
  users: Users,
  x: X,
};

export function Icon({
  name,
  size = 16,
  className,
  style,
}: {
  name: string;
  size?: number;
  className?: string;
  style?: CSSProperties;
}) {
  const Cmp = ICONS[name] ?? Package;
  return <Cmp size={size} strokeWidth={1.75} className={className} style={style} aria-hidden="true" />;
}
