#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORKSPACE_PATH="${CONDUCTOR_WORKSPACE_PATH:-$REPO_ROOT}"
WORKSPACE_NAME="${CONDUCTOR_WORKSPACE_NAME:-$(basename "$WORKSPACE_PATH")}"
BASE_PORT="${CONDUCTOR_PORT:-3000}"

WEB_PORT="$BASE_PORT"
API_PORT="$((BASE_PORT + 1))"
DB_PORT="$((BASE_PORT + 2))"
SHADOW_DB_PORT="$((BASE_PORT + 3))"
STUDIO_PORT="$((BASE_PORT + 4))"
INBUCKET_PORT="$((BASE_PORT + 5))"
EDGE_INSPECTOR_PORT="$((BASE_PORT + 6))"
ANALYTICS_PORT="$((BASE_PORT + 7))"

CONDUCTOR_DIR="$REPO_ROOT/.context/conductor"
SUPABASE_WORKDIR="$CONDUCTOR_DIR/supabase"
SUPABASE_PROJECT_DIR="$SUPABASE_WORKDIR/supabase"
WEB_ENV_FILE="$REPO_ROOT/apps/web/.env.local"
CLI_ENV_FILE="$REPO_ROOT/.env"
GENERATED_MARKER="# Generated by scripts/conductor.sh."

cd "$REPO_ROOT"

log() {
  printf '[conductor] %s\n' "$*"
}

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    printf '[conductor] Missing required command: %s\n' "$1" >&2
    exit 1
  fi
}

ensure_env_writable() {
  local file="$1"

  if [ ! -e "$file" ]; then
    return 0
  fi

  if [ "${CONDUCTOR_OVERWRITE_ENV:-}" = "1" ]; then
    return 0
  fi

  if grep -Fq "$GENERATED_MARKER" "$file"; then
    return 0
  fi

  printf '[conductor] Refusing to overwrite existing non-generated env file: %s\n' "$file" >&2
  printf '[conductor] Move it aside or set CONDUCTOR_OVERWRITE_ENV=1 to replace it.\n' >&2
  exit 1
}

workspace_hash() {
  printf '%s' "$WORKSPACE_PATH" | shasum -a 256 | awk '{ print substr($1, 1, 10) }'
}

sanitize_workspace_name() {
  printf '%s' "$WORKSPACE_NAME" \
    | tr '[:upper:]' '[:lower:]' \
    | sed -E 's/[^a-z0-9]+/-/g; s/-+/-/g; s/^-//; s/-$//'
}

project_id() {
  local hash max_name_len name prefix
  prefix="comp-v2"
  name="$(sanitize_workspace_name)"
  hash="$(workspace_hash)"
  max_name_len="$((40 - ${#prefix} - ${#hash} - 2))"

  if [ -z "$name" ]; then
    name="workspace"
  fi

  if [ "${#name}" -gt "$max_name_len" ]; then
    name="${name:0:$max_name_len}"
    name="${name%-}"
  fi

  printf '%s-%s-%s' "$prefix" "$name" "$hash"
}

ensure_tooling() {
  require_command node
  require_command corepack
  require_command python3
  require_command curl
  require_command docker
  require_command shasum
  require_command supabase
}

enable_corepack() {
  log "Enabling Corepack"
  corepack enable
}

install_dependencies() {
  require_command pnpm
  log "Installing dependencies"
  pnpm install
}

prepare_supabase_workdir() {
  local id web_url api_url
  id="$(project_id)"
  web_url="http://127.0.0.1:${WEB_PORT}"
  api_url="http://127.0.0.1:${API_PORT}"

  mkdir -p "$SUPABASE_PROJECT_DIR"

  ln -sfn "$REPO_ROOT/supabase/migrations" "$SUPABASE_PROJECT_DIR/migrations"
  ln -sfn "$REPO_ROOT/supabase/seed.sql" "$SUPABASE_PROJECT_DIR/seed.sql"

  cat >"$SUPABASE_PROJECT_DIR/config.toml" <<EOF
# Generated by scripts/conductor.sh. Do not edit by hand.
project_id = "$id"

[api]
enabled = true
port = $API_PORT
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = $DB_PORT
shadow_port = $SHADOW_DB_PORT
major_version = 15

[studio]
enabled = true
port = $STUDIO_PORT
api_url = "$api_url"

[inbucket]
enabled = true
port = $INBUCKET_PORT

[auth]
enabled = true
site_url = "$web_url"
additional_redirect_urls = ["$web_url/auth/callback"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
enable_confirmations = false

[storage]
enabled = true
file_size_limit = "25MiB"

[edge_runtime]
enabled = true
inspector_port = $EDGE_INSPECTOR_PORT

[analytics]
enabled = true
port = $ANALYTICS_PORT
backend = "postgres"
EOF
}

supabase_project_id() {
  project_id
}

start_supabase() {
  prepare_supabase_workdir
  log "Using isolated Supabase project $(supabase_project_id)"
  log "Starting isolated Supabase stack on ports ${API_PORT}-${ANALYTICS_PORT}"
  supabase start --workdir "$SUPABASE_WORKDIR"
  ensure_storage_gateway
}

reset_supabase_db() {
  local output_file exit_code
  output_file="$(mktemp)"

  log "Resetting isolated Supabase database"
  set +e
  supabase db reset --workdir "$SUPABASE_WORKDIR" >"$output_file" 2>&1
  exit_code="$?"
  set -e

  if [ "$exit_code" -eq 0 ]; then
    cat "$output_file"
    ensure_storage_gateway
    rm -f "$output_file"
    return 0
  fi

  if grep -q 'Restarting containers' "$output_file" && grep -q 'Error status 502' "$output_file"; then
    sed '/Error status 502/,$d' "$output_file"
    log "Supabase reset completed migrations and seed; waiting for the restarted stack"
    wait_for_supabase_status
    ensure_storage_gateway
    rm -f "$output_file"
    return 0
  fi

  cat "$output_file" >&2
  rm -f "$output_file"
  return "$exit_code"
}

status_json() {
  supabase status --workdir "$SUPABASE_WORKDIR" -o json \
    | python3 -c 'import sys
raw = sys.stdin.read()
start = raw.find("{")
end = raw.rfind("}")
if start == -1 or end == -1 or end < start:
    raise SystemExit("Supabase status did not include JSON")
print(raw[start:end + 1])
'
}

json_value() {
  local key="$1"
  python3 -c 'import json,sys; print(json.load(sys.stdin).get(sys.argv[1], ""))' "$key"
}

wait_for_supabase_status() {
  local attempt status api_url

  for attempt in $(seq 1 30); do
    if status="$(status_json 2>/dev/null)"; then
      api_url="$(printf '%s' "$status" | json_value API_URL)"
      if [ -n "$api_url" ]; then
        log "Supabase stack recovered"
        return 0
      fi
    fi

    sleep 1
  done

  printf '[conductor] Supabase stack did not recover after db reset\n' >&2
  exit 1
}

storage_gateway_code() {
  curl -s -o /dev/null -w '%{http_code}' --max-time 5 "http://127.0.0.1:${API_PORT}/storage/v1/bucket" 2>/dev/null || true
}

ensure_storage_gateway() {
  local attempt code kong
  kong="supabase_kong_$(supabase_project_id)"

  for attempt in $(seq 1 20); do
    code="$(storage_gateway_code)"
    case "$code" in
      200|400|401|403)
        return 0
        ;;
    esac
    sleep 1
  done

  log "Restarting Supabase gateway so Storage is reachable"
  docker restart "$kong" >/dev/null

  for attempt in $(seq 1 20); do
    code="$(storage_gateway_code)"
    case "$code" in
      200|400|401|403)
        log "Supabase Storage gateway is reachable"
        return 0
        ;;
    esac
    sleep 1
  done

  printf '[conductor] Supabase Storage gateway did not become reachable (last HTTP %s)\n' "$code" >&2
  exit 1
}

write_env_files() {
  local status api_url anon_key service_role_key
  status="$(status_json)"
  api_url="$(printf '%s' "$status" | json_value API_URL)"
  anon_key="$(printf '%s' "$status" | json_value ANON_KEY)"
  service_role_key="$(printf '%s' "$status" | json_value SERVICE_ROLE_KEY)"

  if [ -z "$api_url" ] || [ -z "$anon_key" ] || [ -z "$service_role_key" ]; then
    printf '[conductor] Failed to read Supabase status output\n' >&2
    exit 1
  fi

  ensure_env_writable "$WEB_ENV_FILE"
  ensure_env_writable "$CLI_ENV_FILE"

  cat >"$WEB_ENV_FILE" <<EOF
$GENERATED_MARKER
NEXT_PUBLIC_SUPABASE_URL=$api_url
NEXT_PUBLIC_SUPABASE_ANON_KEY=$anon_key
SUPABASE_SERVICE_ROLE_KEY=$service_role_key
EOF

  cat >"$CLI_ENV_FILE" <<EOF
$GENERATED_MARKER
COMPANION_SUPABASE_URL=$api_url
COMPANION_SUPABASE_ANON_KEY=$anon_key
NEXT_PUBLIC_SUPABASE_URL=$api_url
NEXT_PUBLIC_SUPABASE_ANON_KEY=$anon_key
SUPABASE_SERVICE_ROLE_KEY=$service_role_key
EOF

  log "Wrote $WEB_ENV_FILE and $CLI_ENV_FILE"
}

run_web() {
  require_command pnpm
  log "Starting web on http://127.0.0.1:${WEB_PORT}"
  pnpm --filter @companion/web exec next dev --hostname 127.0.0.1 --port "$WEB_PORT"
}

setup() {
  ensure_tooling
  enable_corepack
  install_dependencies
  start_supabase
  reset_supabase_db
  write_env_files
}

run() {
  ensure_tooling
  enable_corepack
  start_supabase
  write_env_files
  run_web
}

archive() {
  local id output_file exit_code remaining
  require_command supabase
  require_command docker
  prepare_supabase_workdir
  id="$(supabase_project_id)"
  output_file="$(mktemp)"

  log "Stopping isolated Supabase project $id"
  set +e
  supabase stop --project-id "$id" --no-backup >"$output_file" 2>&1
  exit_code="$?"
  set -e

  remaining="$(docker ps --format '{{.Names}}' | grep -E "^supabase_.*_${id}$" || true)"
  if [ -n "$remaining" ]; then
    cat "$output_file" >&2
    printf '[conductor] Supabase containers are still running for project %s:\n%s\n' "$id" "$remaining" >&2
    rm -f "$output_file"
    exit 1
  fi

  if [ "$exit_code" -ne 0 ]; then
    cat "$output_file" >&2
    printf '[conductor] supabase stop exited with %s, but no running containers remain for %s.\n' "$exit_code" "$id" >&2
  fi

  rm -f "$output_file"
}

case "${1:-}" in
  setup)
    setup
    ;;
  run)
    run
    ;;
  archive)
    archive
    ;;
  *)
    printf 'Usage: %s {setup|run|archive}\n' "$0" >&2
    exit 2
    ;;
esac
