#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="${CONDUCTOR_ROOT_PATH:-$WORKSPACE_REPO_ROOT}"

WEB_PORT="3000"
API_PORT="54321"
WEB_ENV_FILE="$REPO_ROOT/apps/web/.env.local"
CLI_ENV_FILE="$REPO_ROOT/.env"
GENERATED_MARKER="# Generated by scripts/conductor.sh."

cd "$REPO_ROOT"

log() {
  printf '[conductor] %s\n' "$*"
}

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    printf '[conductor] Missing required command: %s\n' "$1" >&2
    exit 1
  fi
}

ensure_env_writable() {
  local file="$1"

  if [ ! -e "$file" ]; then
    return 0
  fi

  if [ "${CONDUCTOR_OVERWRITE_ENV:-}" = "1" ]; then
    return 0
  fi

  if grep -Fq "$GENERATED_MARKER" "$file"; then
    return 0
  fi

  printf '[conductor] Refusing to overwrite existing non-generated env file: %s\n' "$file" >&2
  printf '[conductor] Move it aside or set CONDUCTOR_OVERWRITE_ENV=1 to replace it.\n' >&2
  exit 1
}

ensure_tooling() {
  require_command node
  require_command corepack
  require_command python3
  require_command curl
  require_command docker
  require_command supabase
}

enable_corepack() {
  log "Enabling Corepack"
  corepack enable
  require_command pnpm
}

status_json() {
  supabase status -o json \
    | python3 -c 'import sys
raw = sys.stdin.read()
start = raw.find("{")
end = raw.rfind("}")
if start == -1 or end == -1 or end < start:
    raise SystemExit("Supabase status did not include JSON")
print(raw[start:end + 1])
'
}

json_value() {
  local key="$1"
  python3 -c 'import json,sys; print(json.load(sys.stdin).get(sys.argv[1], ""))' "$key"
}

supabase_project_id() {
  awk -F '"' '/^project_id = / { print $2; exit }' supabase/config.toml
}

redact_supabase_output() {
  sed -E \
    -e 's/sb_publishable_[A-Za-z0-9_-]+/[redacted-publishable-key]/g' \
    -e 's/sb_secret_[A-Za-z0-9_-]+/[redacted-secret-key]/g' \
    -e 's/eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+/[redacted-jwt]/g' \
    -e 's/[a-f0-9]{64}/[redacted-hex-secret]/g' \
    -e 's/[a-f0-9]{32}/[redacted-hex-key]/g'
}

wait_for_supabase_status() {
  local attempt api_url status

  for attempt in $(seq 1 30); do
    if status="$(status_json 2>/dev/null)"; then
      api_url="$(printf '%s' "$status" | json_value API_URL)"
      if [ -n "$api_url" ]; then
        log "Supabase stack is reachable"
        return 0
      fi
    fi

    sleep 1
  done

  printf '[conductor] Supabase stack did not become reachable after reset\n' >&2
  exit 1
}

storage_gateway_code() {
  curl -s -o /dev/null -w '%{http_code}' --max-time 5 "http://127.0.0.1:${API_PORT}/storage/v1/bucket" 2>/dev/null || true
}

ensure_storage_gateway() {
  local attempt code kong

  for attempt in $(seq 1 20); do
    code="$(storage_gateway_code)"
    case "$code" in
      200|400|401|403)
        return 0
        ;;
    esac
    sleep 1
  done

  kong="supabase_kong_$(supabase_project_id)"
  if docker ps --format '{{.Names}}' | grep -Fxq "$kong"; then
    log "Restarting Supabase gateway so Storage is reachable"
    docker restart "$kong" >/dev/null

    for attempt in $(seq 1 20); do
      code="$(storage_gateway_code)"
      case "$code" in
        200|400|401|403)
          log "Supabase Storage gateway is reachable"
          return 0
          ;;
      esac
      sleep 1
    done
  fi

  printf '[conductor] Supabase Storage gateway did not become reachable (last HTTP %s)\n' "$code" >&2
  exit 1
}

restart_supabase() {
  local exit_code output_file
  output_file="$(mktemp)"

  log "Stopping existing local Supabase stack"
  supabase stop --no-backup || true

  log "Starting local Supabase stack"
  set +e
  supabase start >"$output_file" 2>&1
  exit_code="$?"
  set -e

  if [ "$exit_code" -eq 0 ]; then
    log "Started local Supabase stack"
    rm -f "$output_file"
    return 0
  fi

  redact_supabase_output <"$output_file" >&2
  rm -f "$output_file"
  return "$exit_code"
}

reset_supabase_db() {
  local exit_code output_file
  output_file="$(mktemp)"

  log "Resetting local Supabase database, migrations, and seed"
  set +e
  supabase db reset --yes >"$output_file" 2>&1
  exit_code="$?"
  set -e

  if [ "$exit_code" -eq 0 ]; then
    cat "$output_file"
    wait_for_supabase_status
    ensure_storage_gateway
    rm -f "$output_file"
    return 0
  fi

  if grep -q 'Restarting containers' "$output_file" && grep -q 'Error status 502' "$output_file"; then
    sed '/Error status 502/,$d' "$output_file"
    log "Supabase reset completed migrations and seed; waiting for the restarted stack"
    wait_for_supabase_status
    ensure_storage_gateway
    rm -f "$output_file"
    return 0
  fi

  cat "$output_file" >&2
  rm -f "$output_file"
  return "$exit_code"
}

write_env_files() {
  local status api_url anon_key service_role_key
  status="$(status_json)"
  api_url="$(printf '%s' "$status" | json_value API_URL)"
  anon_key="$(printf '%s' "$status" | json_value ANON_KEY)"
  service_role_key="$(printf '%s' "$status" | json_value SERVICE_ROLE_KEY)"

  if [ -z "$api_url" ] || [ -z "$anon_key" ] || [ -z "$service_role_key" ]; then
    printf '[conductor] Failed to read Supabase status output\n' >&2
    exit 1
  fi

  ensure_env_writable "$WEB_ENV_FILE"
  ensure_env_writable "$CLI_ENV_FILE"

  cat >"$WEB_ENV_FILE" <<EOF
$GENERATED_MARKER
NEXT_PUBLIC_SUPABASE_URL=$api_url
NEXT_PUBLIC_SUPABASE_ANON_KEY=$anon_key
SUPABASE_SERVICE_ROLE_KEY=$service_role_key
EOF

  cat >"$CLI_ENV_FILE" <<EOF
$GENERATED_MARKER
COMPANION_SUPABASE_URL=$api_url
COMPANION_SUPABASE_ANON_KEY=$anon_key
NEXT_PUBLIC_SUPABASE_URL=$api_url
NEXT_PUBLIC_SUPABASE_ANON_KEY=$anon_key
SUPABASE_SERVICE_ROLE_KEY=$service_role_key
EOF

  log "Wrote $WEB_ENV_FILE and $CLI_ENV_FILE"
}

preflight() {
  ensure_tooling
  ensure_env_writable "$WEB_ENV_FILE"
  ensure_env_writable "$CLI_ENV_FILE"
}

run_web() {
  log "Starting web on http://127.0.0.1:${WEB_PORT}"
  pnpm --filter @companion/web exec next dev --hostname 127.0.0.1 --port "$WEB_PORT"
}

run() {
  preflight
  enable_corepack
  restart_supabase
  reset_supabase_db
  write_env_files
  run_web
}

archive() {
  require_command supabase

  log "Stopping local Supabase stack"
  supabase stop --no-backup || true
}

case "${1:-}" in
  run)
    run
    ;;
  archive)
    archive
    ;;
  *)
    printf 'Usage: %s {run|archive}\n' "$0" >&2
    exit 2
    ;;
esac
